CREATE TABLE optiscout_jobs (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    source_jobinfo_id BIGINT NOT NULL,
    process_id BIGINT NULL,
    job VARCHAR(1000) NULL,
    state VARCHAR(100) NULL,
    start_time DATETIME NULL,
    end_time DATETIME NULL,
    cutting_time_seconds INT NULL,
    machine_name VARCHAR(255) NULL,
    material_name VARCHAR(500) NULL,
    material_thickness DECIMAL(12,4) NULL,
    material_width DECIMAL(12,4) NULL,
    material_length DECIMAL(12,4) NULL,
    material_consumption DECIMAL(16,4) NULL,
    cut_path_length DECIMAL(16,4) NULL,
    movement_length DECIMAL(16,4) NULL,
    act_segment INT NULL,
    total_segments INT NULL,
    act_copy INT NULL,
    total_copies INT NULL,
    source_is_last BOOLEAN NULL,
    source_database VARCHAR(500) NULL,
    source_pc VARCHAR(255) NOT NULL,
    imported_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uq_source_job (source_pc, source_jobinfo_id),
    KEY ix_start_time (start_time),
    KEY ix_end_time (end_time),
    KEY ix_state (state),
    KEY ix_machine_name (machine_name),
    KEY ix_material_name (material_name),
    KEY ix_process_id (process_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
